### ISSUE TITLE
Errors in learnr Supervised_learning

### ISSUE THREAD

**Issue by RifatMehreen** [compstat-lmu/lecture_i2ml_learnr_tutorials#41]
In supervised learning section "[more methods](https://compstat-lmu.shinyapps.io/tutorial-supervised-classification/#section-more-methods)" for **(P) Qualitative comparison of LDA, QDA, and naive Bayes** the image is not shown properly. I have marked it in the image below.

![img_1](https://user-images.githubusercontent.com/21968577/74681173-0013ed80-51c3-11ea-963c-f0ec608f193b.PNG)

**Comment by tpielok** [comment]
Yes, this can be closed.
